# Generated by Django 4.0.1 on 2022-11-06 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroomfolder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroomfolder',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='category'),
        ),
    ]
