# Generated by Django 4.0.1 on 2022-12-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroomfolder', '0002_classroomfolder_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroomfolder',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='code'),
        ),
    ]
