# Generated by Django 4.0.1 on 2022-10-17 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enrolled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(default=0.0, verbose_name='no_people')),
                ('code', models.CharField(blank=True, max_length=255, null=True, verbose_name='code')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
