# Generated by Django 4.0.1 on 2022-10-23 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrolled', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolled',
            name='student_id',
            field=models.IntegerField(default=0.0, verbose_name='student_id'),
        ),
    ]
