# Generated by Django 4.0.1 on 2022-11-04 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrolled', '0002_alter_enrolled_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolled',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='status'),
        ),
    ]
