# Generated by Django 4.0.1 on 2022-10-22 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroomfiles', '0002_classroomfiles_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroomfiles',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='file_name'),
        ),
    ]
