# Generated by Django 4.0.1 on 2022-11-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroomfiles', '0004_classroomfiles_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroomfiles',
            name='percent_from',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='percent_from'),
        ),
    ]
