# Generated by Django 4.0.1 on 2022-11-06 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroomfiles', '0005_classroomfiles_percent_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroomfiles',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='category'),
        ),
    ]
