# Generated by Django 4.0.1 on 2022-11-06 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroomfiles', '0006_classroomfiles_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroomfiles',
            name='category',
        ),
    ]
