# Generated by Django 4.0.1 on 2022-10-17 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='class_name')),
                ('code', models.CharField(blank=True, max_length=255, null=True, verbose_name='code')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
