# Generated by Django 4.0.1 on 2022-10-17 02:53

from django.db import migrations, models
import localfiles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocalFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0.0, verbose_name='user_id')),
                ('files', models.FileField(default='uploads/users_placeholder.png', upload_to=localfiles.models.nameFile, verbose_name='files')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
