# Generated by Django 4.0.1 on 2022-10-17 02:53

from django.db import migrations, models
import todo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes', models.IntegerField(default=0.0, verbose_name='classes')),
                ('task_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='task_name')),
                ('files', models.FileField(default='uploads/users_placeholder.png', upload_to=todo.models.nameFile, verbose_name='files')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
